services:
  - type: web
    name: loyalty-mvp-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: backend
      - key: SECRET_KEY
        generateValue: true
      - key: DEV_RETURN_OTP_IN_RESPONSE
        value: "true"
